CREATE TABLE `brd_log_row_data` (
    `id` bigint(20) unsigned NOT NULL COMMENT 'ID',
    `eventrecvtime` varchar(100) DEFAULT NULL COMMENT '事件接收时间',
    `eventgeneratetime` varchar(100) DEFAULT NULL COMMENT '事件产生时间',
    `eventdurationtime` varchar(100) DEFAULT NULL COMMENT '事件持续时间，单位秒',
    `username` varchar(100) DEFAULT NULL COMMENT '用户名称',
    `srcipaddress` varchar(100) DEFAULT NULL COMMENT '源IP地址',
    `srcmacaddress` varchar(100) DEFAULT NULL COMMENT '源MAC地址',
    `srcport` varchar(100) DEFAULT NULL COMMENT '源端口',
    `operation` varchar(100) DEFAULT NULL COMMENT '操作',
    `destipaddress` varchar(100) DEFAULT NULL COMMENT '目的IP地址',
    `destmacaddress` varchar(100) DEFAULT NULL COMMENT '目的MAC地址',
    `destport` varchar(100) DEFAULT NULL COMMENT '目的端口',
    `eventname` varchar(200) DEFAULT NULL COMMENT '事件名称',
    `firsteventtype` varchar(100) DEFAULT NULL COMMENT '一级事件类型',
    `secondeventtype` varchar(100) DEFAULT NULL COMMENT '二级事件类型',
    `thirdeventtype` varchar(100) DEFAULT NULL COMMENT '三级事件类型',
    `eventdesc` text COMMENT '事件摘要',
    `eventgrade` varchar(100) DEFAULT NULL COMMENT '事件等级',
    `networkprotocal` varchar(100) DEFAULT NULL COMMENT '网络协议，例如TCP,UDP,ICMP等等',
    `netappprotocal` varchar(100) DEFAULT NULL COMMENT '网络应用协议，例如tp,sftp,http,https,pop3,imap等等 ',
    `deviceipaddress` varchar(100) DEFAULT NULL COMMENT '设备IP地址',
    `devicename` varchar(200) DEFAULT NULL COMMENT '设备名称',
    `devicetype` varchar(200) DEFAULT NULL COMMENT '设备类型',
    `devicefactory` varchar(200) DEFAULT NULL COMMENT '设备厂家',
    `devicemodel` varchar(200) DEFAULT NULL COMMENT '设备型号',
    `pid` varchar(20) DEFAULT NULL COMMENT '进程ID，也就是导致产生此日志操作的进程ID',
    `url` varchar(255) DEFAULT NULL COMMENT '威胁情报库url',
    `domain` varchar(255) DEFAULT NULL COMMENT '威胁情报库域名',
    `mail` varchar(200) DEFAULT NULL COMMENT '威胁情报库邮箱地址',
    `malwaresample` text COMMENT '威胁情报库勒索软件恶意软件样本数据',
    `softwarename` varchar(200) DEFAULT NULL COMMENT '软件名称',
    `softwareversion` varchar(20) DEFAULT NULL COMMENT '软件版本',
    `reserved1` varchar(200) DEFAULT NULL COMMENT '保留字段1',
    `reserved2` varchar(200) DEFAULT NULL COMMENT '保留字段2',
    `reserved3` varchar(200) DEFAULT NULL COMMENT '保留字段3',
    `reserved4` varchar(200) DEFAULT NULL COMMENT '保留字段4',
    `reserved5` varchar(200) DEFAULT NULL COMMENT '保留字段5',
    `reserved6` varchar(200) DEFAULT NULL COMMENT '保留字段6',
    `reserved7` varchar(200) DEFAULT NULL COMMENT '保留字段7',
    `reserved8` varchar(200) DEFAULT NULL COMMENT '保留字段8',
    `reserved9` varchar(200) DEFAULT NULL COMMENT '保留字段9',
    `reserved10` varchar(200) DEFAULT NULL COMMENT '保留字段10',
    `reserved11` int(11) DEFAULT NULL COMMENT '保留字段11',
    `reserved12` int(11) DEFAULT NULL COMMENT '保留字段12',
    `reserved13` int(11) DEFAULT NULL COMMENT '保留字段13',
    `reserved14` bigint(20) DEFAULT NULL COMMENT '保留字段14',
    `reserved15` bigint(20) DEFAULT NULL COMMENT '保留字段15',
    `reserved16` bigint(20) DEFAULT NULL COMMENT '保留字段16',
    `regex` varchar(255) DEFAULT NULL,
    `uuid` varchar(255) DEFAULT NULL,
    `rulename` varchar(255) DEFAULT NULL,
    `bytes` varchar(255) DEFAULT NULL,
    `component_name_and_banner` varchar(255) DEFAULT NULL,
    `destas` varchar(255) DEFAULT NULL,
    `direction` varchar(255) DEFAULT NULL,
    `dmask` varchar(255) DEFAULT NULL,
    `dnsdomainname` varchar(255) DEFAULT NULL,
    `dnstime` varchar(255) DEFAULT NULL,
    `dnstype` varchar(255) DEFAULT NULL,
    `dtos` varchar(255) DEFAULT NULL,
    `end_time` varchar(255) DEFAULT NULL,
    `flows` varchar(255) DEFAULT NULL,
    `fwd` varchar(255) DEFAULT NULL,
    `groupid` varchar(255) DEFAULT NULL,
    `icp_record` varchar(255) DEFAULT NULL,
    `icpsite_name` varchar(255) DEFAULT NULL,
    `icpwebsite` varchar(255) DEFAULT NULL,
    `inputint` varchar(255) DEFAULT NULL,
    `ipaddrs` text,
    `location` varchar(255) DEFAULT NULL,
    `nextip` varchar(255) DEFAULT NULL,
    `outputint` varchar(255) DEFAULT NULL,
    `packets` varchar(255) DEFAULT NULL,
    `risk_level` varchar(255) DEFAULT NULL,
    `smask` varchar(255) DEFAULT NULL,
    `sourceas` varchar(255) DEFAULT NULL,
    `start_time` varchar(255) DEFAULT NULL,
    `stos` varchar(255) DEFAULT NULL,
    `target` varchar(255) DEFAULT NULL,
    `task_name` varchar(255) DEFAULT NULL,
    `tcpflags` varchar(255) DEFAULT NULL,
    `vulnerabilitydetailfilename` varchar(255) DEFAULT NULL,
    `vulnerabilityemergent` varchar(255) DEFAULT NULL,
    `vulnerabilityhigh` varchar(255) DEFAULT NULL,
    `vulnerabilityinfo` varchar(255) DEFAULT NULL,
    `vulnerabilitylow` varchar(255) DEFAULT NULL,
    `vulnerabilitymiddle` varchar(255) DEFAULT NULL,
    `vulnerabilitytotal` varchar(255) DEFAULT NULL,
    `websiteurl` varchar(255) DEFAULT NULL,
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC