CREATE TABLE IF NOT EXISTS asset_base(
    device_ip varchar(64) COMMENT '资产IP',
    device_mac varchar(256) COMMENT '资产MAC地址',
    asset_id varchar(255) COMMENT 'ip+mac',
    device_name varchar(64) COMMENT '资产名称',
    device_ip_ownership varchar(255) DEFAULT "" COMMENT 'ip归属地',
    device_type varchar(64) COMMENT '资产类型，ID与label表关联',
    physical_address varchar(64) COMMENT '',
    machine_room varchar(64) COMMENT '机房',
    machine_box varchar(64) COMMENT '机架',
    manufacturers varchar(64) COMMENT '制造厂商',
    sn varchar(64) COMMENT 'SN编号',
    model varchar(64) COMMENT '型号',
    business_system varchar(64) COMMENT '',
    responsible_person varchar(16) COMMENT '责任人',
    responsible_telephone varchar(32) COMMENT '责任人电话',
    asset_desc varchar(1024) COMMENT '资产描述',
    confidentiality varchar(64) COMMENT '保密性',
    integrality varchar(64) COMMENT '完整性',
    usability varchar(64) COMMENT '可用性',
    importance varchar(64) COMMENT '重要性',
    permitted varchar(64) COMMENT '是否纳管 0：未知 1：已纳管',
    longitude varchar(64) COMMENT '经度',
    latitude varchar(64) COMMENT '维度',
    responsible_unit varchar(64) COMMENT '责任人单元',
    responsible_department varchar(64) COMMENT '责任人所属部门',
    responsible_group varchar(64) COMMENT '责任人所属组',
    data_base_info varchar(65532) COMMENT '数据库信息',
    kernel_version varchar(255) COMMENT '内核版本号',
    message_oriented_middleware varchar(65532) COMMENT '消息中间件',
    open_service_of_port varchar(65532) COMMENT '服务信息及端口号',
    os_info varchar(65532) COMMENT '操作系统信息',
    patch_properties varchar(65532) COMMENT '补丁属性',
    program_info varchar(65532) COMMENT '进程信息',
    system_fingerprint_info varchar(65532) COMMENT '系统指纹信息',
    label_id varchar(255) DEFAULT "" COMMENT '标签ID',
    label_type1 varchar(255) DEFAULT "" COMMENT'一级标签',
    label_type2 varchar(255) DEFAULT "" COMMENT'二级标签',
    update_time varchar(64) COMMENT '更新时间'
)
UNIQUE KEY(`device_ip`, `device_mac`)
DISTRIBUTED BY HASH(device_ip,device_mac) BUCKETS 8;